// "use client"
import { Inter } from 'next/font/google'
import './globals.css'
import TopBar from "@/app/layout/TopBar";

const inter = Inter({ subsets: ['latin'] })

// Remove the export statement for "metadata"
// export const metadata = {
//   title: 'BookStore Application',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <TopBar />
      {children}
      </body>
      </html>
  )
}
